# Configuración de despliegue de imagen del componente
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mongo-database-component
spec:
  selector:
    matchLabels:
      app: backend-mongo-database-component
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-mongo-database-component
    spec:
      containers:
        - name: mongo-database
          image: mongo:3.6-xenial # PARAM-1: Imagen y versión a desplegar de base de datos
          #resources: #TODO: Configurar límites de uso de recursos.
          #  limits:
          #    memory: "200Mi"
          #  requests:
          #    memory: "100Mi"
          #command: ["stress"]
          #args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          #persistentVolumeClaim:
          #  claimName: database-storage-pvc
          awsElasticBlockStore:
            volumeID: vol-0aae0337012d54484 # PARAM-2: ID del volumen EBS que tiene los datos de la base de datos del ambiente
            fsType: ext4

---
# Requerimientos de almacenamiento para la base de datos
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: database-storage-pvc
#spec:
  #storageClassName: from-backup-database-storage-ssd
#  storageClassName: database-storage-ssd
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 7Gi # PARAM-2: Tamaño de almacenamiento a reservar

---
# Volumen de almacenamiento para la base de datos
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: database-storage-pv
#  labels:
#    type: EBS
#spec:
#  storageClassName: from-backup-database-storage-ssd
#  capacity:
#    storage: 7Gi # PARAM-3: Tamaño real del volumen
#accessModes:
#  - ReadWriteOnce
#awsElasticBlockStore:
#  volumeID: vol-050c09096df2a1d2c # PARAM-4: ID del volumen EBS
#  fsType: ext4

---
# Tipo de almacenamiento
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: database-storage-ssd
#provisioner: kubernates.io/aws-ebs
#parameters:
#  type: gp2

---
# Configuración del servicio de base de datos
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: backend-mongo-database-component
  ports:
    - name: mongo-database
      port: 27017 # PARAM-3: Puerto de acceso a la base de datos
  type: LoadBalancer
