# Configuración de almacenamiento para bases de datos
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: database-storage-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
